// ── Decoder Unit Tests ──────────────────────────────────────────────────────
// Tests for AvDecoder (libavformat/libavcodec/libswresample) and ReplayGain
// (EBU R128 loudness analysis).
//
// Requires test files generated by ffmpeg:
//   ffmpeg -f lavfi -i "sine=frequency=440:duration=1" -ar 44100 -ac 1 -sample_fmt s16 /tmp/test_tone.wav
//   ffmpeg -f lavfi -i "sine=frequency=440:duration=1" -ar 44100 -ac 2 /tmp/test_tone.flac

#include <cassert>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>

#include "src/decoder/AvDecoder.h"
#include "src/decoder/ReplayGain.h"

namespace ead = echo_audio_daemon;

// ── Test paths ──────────────────────────────────────────────────────────────
static const std::string kTestWav  = "/tmp/test_tone.wav";
static const std::string kTestFlac = "/tmp/test_tone.flac";

// ── Helpers ─────────────────────────────────────────────────────────────────
#define CHECK(expr)                                                       \
    do {                                                                   \
        if (!(expr)) {                                                     \
            std::cerr << "FAIL [" << __FILE__ << ":" << __LINE__ << "] "  \
                      << #expr << "\n";                                    \
            return 1;                                                      \
        }                                                                  \
    } while (false)

#define CHECK_CLOSE(a, b, eps)                                            \
    do {                                                                   \
        double _a = (a), _b = (b), _eps = (eps);                          \
        if (std::fabs(_a - _b) > _eps) {                                  \
            std::cerr << "FAIL [" << __FILE__ << ":" << __LINE__ << "] "  \
                      << "expected " << _b << " ± " << _eps               \
                      << ", got " << _a << "\n";                           \
            return 1;                                                      \
        }                                                                  \
    } while (false)

// ── Test: probe WAV file ────────────────────────────────────────────────────
static int test_probe_wav() {
    std::cout << "  test_probe_wav...\n";

    auto fmt = ead::AvDecoder::probe(kTestWav);
    CHECK(!fmt.format.empty());
    CHECK(fmt.sampleRate == 44100);
    CHECK(fmt.channels == 1);
    CHECK_CLOSE(fmt.duration, 1.0, 0.05);
    CHECK(!fmt.codec.empty());

    std::cout << "    format=" << fmt.format
              << " codec=" << fmt.codec
              << " sr=" << fmt.sampleRate
              << " ch=" << fmt.channels
              << " dur=" << fmt.duration << "\n";
    return 0;
}

// ── Test: probe FLAC file ──────────────────────────────────────────────────
static int test_probe_flac() {
    std::cout << "  test_probe_flac...\n";

    auto fmt = ead::AvDecoder::probe(kTestFlac);
    CHECK(!fmt.format.empty());
    CHECK(fmt.sampleRate == 44100);
    CHECK(fmt.channels == 2);
    CHECK_CLOSE(fmt.duration, 1.0, 0.05);
    CHECK(!fmt.codec.empty());

    std::cout << "    format=" << fmt.format
              << " codec=" << fmt.codec
              << " sr=" << fmt.sampleRate
              << " ch=" << fmt.channels
              << " dur=" << fmt.duration << "\n";
    return 0;
}

// ── Test: probe non-existent file returns empty format ─────────────────────
static int test_probe_nonexistent() {
    std::cout << "  test_probe_nonexistent...\n";

    auto fmt = ead::AvDecoder::probe("/tmp/nonexistent_audio_file.xyz");
    CHECK(fmt.format.empty());
    CHECK(fmt.sampleRate == 0);
    CHECK(fmt.channels == 0);
    return 0;
}

// ── Helper: decode all frames using appropriately sized buffer ─────────────
static int decodeAll(ead::AvDecoder& decoder) {
    int channels = decoder.getChannels();
    int bufFrames = 8192;  // frames per batch
    std::vector<float> buf(static_cast<size_t>(bufFrames) * channels);
    int totalFrames = 0;
    while (true) {
        int frames = decoder.decode(buf.data(), bufFrames);
        if (frames <= 0) break;
        totalFrames += frames;
    }
    return totalFrames;
}

// ── Test: decode WAV file ──────────────────────────────────────────────────
static int test_decode_wav() {
    std::cout << "  test_decode_wav...\n";

    ead::AvDecoder decoder;
    CHECK(decoder.open(kTestWav));
    CHECK(decoder.isOpen());
    CHECK(decoder.getSampleRate() == 44100);
    CHECK(decoder.getChannels() == 1);

    // Decode the entire file (should be ~44100 frames for 1s @ 44100)
    int totalFrames = decodeAll(decoder);

    std::cout << "    total frames: " << totalFrames << "\n";
    // Allow some tolerance for encoder padding
    CHECK_CLOSE(static_cast<double>(totalFrames), 44100.0, 2000.0);

    decoder.close();
    CHECK(!decoder.isOpen());
    return 0;
}

// ── Test: decode FLAC file (stereo) ────────────────────────────────────────
static int test_decode_flac() {
    std::cout << "  test_decode_flac...\n";

    ead::AvDecoder decoder;
    CHECK(decoder.open(kTestFlac));
    CHECK(decoder.isOpen());
    CHECK(decoder.getChannels() == 2);

    // Verify first decoded batch has non-zero interleaved data
    int bufFrames = 4096;
    std::vector<float> buf(static_cast<size_t>(bufFrames) * 2);
    int frames = decoder.decode(buf.data(), bufFrames);
    CHECK(frames > 0);
    bool hasSignal = false;
    for (int i = 0; i < frames * 2; ++i) {
        if (std::fabs(buf[i]) > 1e-6f) {
            hasSignal = true;
            break;
        }
    }
    CHECK(hasSignal);

    // Decode rest
    int totalFrames = frames;
    while (true) {
        frames = decoder.decode(buf.data(), bufFrames);
        if (frames <= 0) break;
        totalFrames += frames;
    }

    std::cout << "    total frames: " << totalFrames << "\n";
    CHECK_CLOSE(static_cast<double>(totalFrames), 44100.0, 2000.0);

    decoder.close();
    return 0;
}

// ── Test: decode with target sample rate ───────────────────────────────────
static int test_decode_resample() {
    std::cout << "  test_decode_resample...\n";

    ead::AvDecoder decoder;
    // Request 22050 Hz output from 44100 Hz source
    CHECK(decoder.open(kTestWav, 22050, 0));
    CHECK(decoder.getSampleRate() == 22050);
    CHECK(decoder.getChannels() == 1);

    int totalFrames = decodeAll(decoder);

    // 1 second at 22050 Hz ≈ 22050 frames
    std::cout << "    total frames at 22050Hz: " << totalFrames << "\n";
    CHECK_CLOSE(static_cast<double>(totalFrames), 22050.0, 1000.0);

    decoder.close();
    return 0;
}

// ── Test: seek within file ─────────────────────────────────────────────────
static int test_seek() {
    std::cout << "  test_seek...\n";

    ead::AvDecoder decoder;
    CHECK(decoder.open(kTestWav));

    // Seek to 0.5 seconds
    CHECK(decoder.seek(0.5));

    // Decode a small buffer and check position
    std::vector<float> buf(1024);
    int frames = decoder.decode(buf.data(), 1024);
    CHECK(frames > 0);

    // A 440Hz sine wave at 0.5s should have non-zero data
    bool hasSignal = false;
    for (int i = 0; i < frames; ++i) {
        if (std::fabs(buf[i]) > 1e-6f) {
            hasSignal = true;
            break;
        }
    }
    CHECK(hasSignal);

    decoder.close();
    return 0;
}

// ── Test: seek to end returns data (flush) ─────────────────────────────────
static int test_seek_end() {
    std::cout << "  test_seek_end...\n";

    ead::AvDecoder decoder;
    CHECK(decoder.open(kTestWav));

    // Seek near the end (0.95s)
    CHECK(decoder.seek(0.95));

    std::vector<float> buf(4096);
    int frames = decoder.decode(buf.data(), 4096);
    CHECK(frames > 0);

    decoder.close();
    return 0;
}

// ── Test: open/close reopen cycle ──────────────────────────────────────────
static int test_reopen_cycle() {
    std::cout << "  test_reopen_cycle...\n";

    ead::AvDecoder decoder;

    // First cycle (mono WAV)
    CHECK(decoder.open(kTestWav));
    CHECK(decoder.isOpen());
    std::vector<float> buf(512);
    int frames = decoder.decode(buf.data(), 512);
    CHECK(frames > 0);
    decoder.close();
    CHECK(!decoder.isOpen());

    // Second cycle (stereo FLAC)
    CHECK(decoder.open(kTestFlac));
    CHECK(decoder.isOpen());
    CHECK(decoder.getChannels() == 2);
    std::vector<float> buf2(1024);  // 512 frames * 2 channels
    frames = decoder.decode(buf2.data(), 512);
    CHECK(frames > 0);
    decoder.close();
    CHECK(!decoder.isOpen());

    return 0;
}

// ── Test: ReplayGain applyGain modifies samples ────────────────────────────
static int test_replaygain_apply() {
    std::cout << "  test_replaygain_apply...\n";

    // Create a simple signal
    const int kFrames = 100;
    const int kChannels = 2;
    std::vector<float> samples(static_cast<size_t>(kFrames) * kChannels);
    for (int i = 0; i < kFrames * kChannels; ++i) {
        samples[i] = 0.5f;
    }

    // Compute RMS before
    double sumSqBefore = 0.0;
    for (auto s : samples) sumSqBefore += static_cast<double>(s) * s;
    double rmsBefore = std::sqrt(sumSqBefore / samples.size());

    // Apply +3 dB gain
    ead::ReplayGain::applyGain(samples.data(), kFrames, kChannels, 3.0);

    // Compute RMS after
    double sumSqAfter = 0.0;
    for (auto s : samples) sumSqAfter += static_cast<double>(s) * s;
    double rmsAfter = std::sqrt(sumSqAfter / samples.size());

    // +3 dB = ~1.413x multiplier
    double expectedRatio = std::pow(10.0, 3.0 / 20.0);
    CHECK_CLOSE(rmsAfter / rmsBefore, expectedRatio, 0.001);

    return 0;
}

// ── Test: ReplayGain applyGain with negative dB ────────────────────────────
static int test_replaygain_apply_negative() {
    std::cout << "  test_replaygain_apply_negative...\n";

    std::vector<float> samples(100, 0.5f);

    double sumSqBefore = 0.0;
    for (auto s : samples) sumSqBefore += static_cast<double>(s) * s;
    double rmsBefore = std::sqrt(sumSqBefore / samples.size());

    // Apply -6 dB gain (should halve amplitude)
    ead::ReplayGain::applyGain(samples.data(), 100, 1, -6.0);

    double sumSqAfter = 0.0;
    for (auto s : samples) sumSqAfter += static_cast<double>(s) * s;
    double rmsAfter = std::sqrt(sumSqAfter / samples.size());

    double expectedRatio = std::pow(10.0, -6.0 / 20.0); // ~0.5
    CHECK_CLOSE(rmsAfter / rmsBefore, expectedRatio, 0.001);

    return 0;
}

// ── Test: ReplayGain preventClipping ────────────────────────────────────────
static int test_replaygain_prevent_clipping() {
    std::cout << "  test_replaygain_prevent_clipping...\n";

    // Case 1: peak=0.8, targetLufs=-14
    // refGainDb = -18 - (-14) = -4 dB → linear = 0.631
    // peakAfterGain = 0.8 * 0.631 = 0.505 < 1.0 → no scaling
    std::vector<float> s1(100, 0.8f);
    ead::ReplayGain::preventClipping(s1.data(), 100, 1, 0.8, -14.0);
    CHECK_CLOSE(static_cast<double>(s1[0]), 0.8, 0.01);

    // Case 2: peak=0.9, targetLufs=-30 (requires +12dB boost → linear ≈ 3.98)
    // peakAfterGain = 0.9 * 3.98 = 3.58 > 1.0 → scale = 1/3.58 = 0.279
    // samples become 0.9 * 0.279 = 0.251
    std::vector<float> s2(100, 0.9f);
    ead::ReplayGain::preventClipping(s2.data(), 100, 1, 0.9, -30.0);
    CHECK(s2[0] < 0.9f);   // scaled down
    CHECK(s2[0] > 0.0f);
    // Verify all samples scaled identically
    CHECK_CLOSE(static_cast<double>(s2[0]), static_cast<double>(s2[50]), 0.001);

    // Case 3: peak=0.0 → no-op
    std::vector<float> s3(100, 0.0f);
    ead::ReplayGain::preventClipping(s3.data(), 100, 1, 0.0, -14.0);
    CHECK_CLOSE(static_cast<double>(s3[0]), 0.0, 0.001);

    return 0;
}

// ── Test: ReplayGain analyze with actual WAV file ───────────────────────────
static int test_replaygain_analyze() {
    std::cout << "  test_replaygain_analyze...\n";

    auto result = ead::ReplayGain::analyze(kTestWav);

    // A 440Hz sine wave at 0 dBFS should have integrated loudness around -3 to -5 LUFS
    // (sine at full scale is about -3 dBFS)
    std::cout << "    integratedLufs=" << result.integratedLufs
              << " trackGainDb=" << result.trackGainDb
              << " trackPeak=" << result.trackPeak << "\n";

    // The analysis should produce sensible values
    CHECK(result.integratedLufs < 0.0);  // should be negative LUFS
    CHECK(result.trackPeak > 0.1);        // sine wave should have significant amplitude
    CHECK(result.trackPeak <= 1.0);       // peak should not exceed 1.0

    return 0;
}

// ── Test: Decoder state queries before open ─────────────────────────────────
static int test_decoder_initial_state() {
    std::cout << "  test_decoder_initial_state...\n";

    ead::AvDecoder decoder;
    CHECK(!decoder.isOpen());
    CHECK(decoder.getSampleRate() == 0);
    CHECK(decoder.getChannels() == 0);
    CHECK(decoder.getDuration() == 0.0);

    return 0;
}

// ── Test: decode after seek returns correct amount ─────────────────────────
static int test_decode_after_seek_exact() {
    std::cout << "  test_decode_after_seek_exact...\n";

    ead::AvDecoder decoder;
    CHECK(decoder.open(kTestWav));

    // Seek to 0.3s
    CHECK(decoder.seek(0.3));

    // Decode exactly 1024 frames (mono: 1024 floats needed)
    std::vector<float> buf(1024);
    int frames = decoder.decode(buf.data(), 1024);
    CHECK(frames == 1024);

    decoder.close();
    return 0;
}

// ── Main ────────────────────────────────────────────────────────────────────
int main() {
    std::cout << "=== echo-daemon-decoder tests ===\n\n";

    int failures = 0;

    std::cout << "-- AvDecoder --\n";
    failures += test_decoder_initial_state();
    failures += test_probe_wav();
    failures += test_probe_flac();
    failures += test_probe_nonexistent();
    failures += test_decode_wav();
    failures += test_decode_flac();
    failures += test_decode_resample();
    failures += test_seek();
    failures += test_seek_end();
    failures += test_decode_after_seek_exact();
    failures += test_reopen_cycle();

    std::cout << "\n-- ReplayGain --\n";
    failures += test_replaygain_apply();
    failures += test_replaygain_apply_negative();
    failures += test_replaygain_prevent_clipping();
    failures += test_replaygain_analyze();

    std::cout << "\n";
    if (failures == 0) {
        std::cout << "All tests passed.\n";
        return 0;
    }
    std::cerr << failures << " test(s) failed.\n";
    return 1;
}
