import { PRESET_THEMES } from "../utils/color";

export const DEFAULT_CONFIG = {
  language: "en",
  showVisualizer: true,
  showMiniWaveform: true,
  useEQ: true,
  eqBands: [
    { id: 1, type: "lowshelf", freq: 32, gain: 0, q: 1.0, enabled: true },
    { id: 2, type: "peaking", freq: 64, gain: 0, q: 1.4, enabled: true },
    { id: 3, type: "peaking", freq: 125, gain: 0, q: 1.4, enabled: true },
    { id: 4, type: "peaking", freq: 250, gain: 0, q: 1.4, enabled: true },
    { id: 5, type: "peaking", freq: 500, gain: 0, q: 1.4, enabled: true },
    { id: 6, type: "peaking", freq: 1000, gain: 0, q: 1.4, enabled: true },
    { id: 7, type: "peaking", freq: 2000, gain: 0, q: 1.4, enabled: true },
    { id: 8, type: "peaking", freq: 4000, gain: 0, q: 1.4, enabled: true },
    { id: 9, type: "peaking", freq: 8000, gain: 0, q: 1.4, enabled: true },
    { id: 10, type: "highshelf", freq: 16000, gain: 0, q: 1.0, enabled: true },
  ],
  visualizerStyle: "bars",
  showDiscordRPC: true,
  enableMV: false,
  customBgPath: null,
  customBgOpacity: 1.0,
  uiBgOpacity: 0.6,
  uiBlur: 20,
  uiFontFamily: "outfit",
  uiCustomFontFamily: "",
  uiBaseFontSize: 15,
  uiRadiusScale: 1,
  uiShadowIntensity: 1,
  uiSaturation: 1,
  uiAccentBackgroundGlow: true,
  theme: "sakura",
  customColors: { ...PRESET_THEMES.sakura.colors },
  mvAsBackground: false,
  mvBackgroundOpacity: 0.8,
  mvMuted: true,
  autoFallbackToBilibili: true,
  lyricsShadow: true,
  lyricsShadowOpacity: 0.6,
  lyricsShowRomaji: true,
  lyricsShowTranslation: true,
  lyricsFontSize: 32,
  lyricsSource: "lrclib",
  lyricsOffsetMs: 0,
  preamp: 0,
  activePreset: "Custom",
  enableDiscordRPC: true,
  /** 歌单导入（如网易云）保存音频的目录；为 null 时使用 downloadFolder */
  playlistImportFolder: null,
};
