export const REPLAY_GAIN_ANALYSIS_VERSION = 1;
export const DEFAULT_REPLAY_GAIN_TARGET_LUFS = -14;
export const SPOTIFY_NORMAL_REPLAY_GAIN_TARGET_LUFS = -14;
export const QUIET_REPLAY_GAIN_TARGET_LUFS = -18;
