# CMake generated Testfile for 
# Source directory: /home/uright/ECHO/native/echo-audio-daemon/tests
# Build directory: /home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[echo-daemon-miniaudio]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-miniaudio-tests")
set_tests_properties([=[echo-daemon-miniaudio]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;150;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-types]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-tests")
set_tests_properties([=[echo-daemon-types]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;152;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-ipc]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-ipc-tests")
set_tests_properties([=[echo-daemon-ipc]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;153;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-null-output]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-null-output-tests")
set_tests_properties([=[echo-daemon-null-output]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;154;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-harness]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-harness")
set_tests_properties([=[echo-daemon-harness]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;155;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-device-enumerator]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-device-enumerator-tests")
set_tests_properties([=[echo-daemon-device-enumerator]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;156;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-device-watcher]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-device-watcher-tests")
set_tests_properties([=[echo-daemon-device-watcher]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;157;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-harness-runner]=] "/home/uright/ECHO/native/echo-audio-daemon/tests/harness_runner.sh" "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/src/echo-audio-daemon")
set_tests_properties([=[echo-daemon-harness-runner]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;158;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-wasapi-exclusive]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-wasapi-exclusive-tests")
set_tests_properties([=[echo-daemon-wasapi-exclusive]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;203;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-decoder]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-decoder-tests")
set_tests_properties([=[echo-daemon-decoder]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;234;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-biquad]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-biquad-tests")
set_tests_properties([=[echo-daemon-biquad]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;248;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-eq]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-eq-tests")
set_tests_properties([=[echo-daemon-eq]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;263;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-session-manager]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-session-manager-tests")
set_tests_properties([=[echo-daemon-session-manager]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;300;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-convolution]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-convolution-tests")
set_tests_properties([=[echo-daemon-convolution]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;319;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-channel-balance]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-channel-balance-tests")
set_tests_properties([=[echo-daemon-channel-balance]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;333;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-limiter]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-limiter-tests")
set_tests_properties([=[echo-daemon-limiter]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;347;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
add_test([=[echo-daemon-dsp-pipeline]=] "/home/uright/ECHO/native/echo-audio-daemon/build-noasan/tests/echo-daemon-dsp-pipeline-tests")
set_tests_properties([=[echo-daemon-dsp-pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;369;add_test;/home/uright/ECHO/native/echo-audio-daemon/tests/CMakeLists.txt;0;")
