/**
 * Preset theme audit: WCAG contrast (text vs bg / glass), bg gradient strength,
 * and pairwise accent similarity (flags themes that may look alike).
 *
 * Run: node scripts/theme-audit.mjs
 * Optional: THEME_AUDIT_MD=1 writes scripts/theme-audit-report.md
 */
import { writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath, pathToFileURL } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const toUrl = (p) => pathToFileURL(p).href

const { PRESET_THEMES, relativeLuminance, hexToRgb } = await import(
  toUrl(join(root, 'src/renderer/src/utils/color.js'))
)
const { normalizeThemeColors } = await import(
  toUrl(join(root, 'src/renderer/src/utils/themeColors.js'))
)

function contrastRatio(hexFg, hexBg) {
  const L1 = relativeLuminance(hexFg)
  const L2 = relativeLuminance(hexBg)
  const light = Math.max(L1, L2)
  const dark = Math.min(L1, L2)
  return (light + 0.05) / (dark + 0.05)
}

/** Euclidean distance in 8-bit RGB space (typical visible gradient step is tens of units). */
function hexDistance(a, b) {
  const A = hexToRgb(a)
  const B = hexToRgb(b)
  const dr = (A.r - B.r) * 255
  const dg = (A.g - B.g) * 255
  const db = (A.b - B.b) * 255
  return Math.sqrt(dr * dr + dg * dg + db * db)
}

function accentFingerprint(colors) {
  const { accent1, accent2, accent3 } = colors
  const v = [accent1, accent2, accent3].map((h) => {
    const { r, g, b } = hexToRgb(h)
    return [r, g, b]
  })
  const flat = v.flat()
  const norm = Math.sqrt(flat.reduce((s, x) => s + x * x, 0)) || 1
  return flat.map((x) => x / norm)
}

function cosineSimilarity(a, b) {
  let s = 0
  for (let i = 0; i < a.length; i++) s += a[i] * b[i]
  return s
}

function main() {
  const ids = Object.keys(PRESET_THEMES)
  const lines = []
  const push = (s) => {
    lines.push(s)
    console.log(s)
  }

  push('# Theme preset audit (generated by scripts/theme-audit.mjs)\n')
  push('## Contrast (WCAG ratio; AA text ≥ 4.5:1 for normal UI copy)\n')
  push(
    '| Theme | textMain vs bg | textSoft vs bg | textMain vs glass | textSoft vs glass | gradient ΔRGB |'
  )
  push('| --- | ---: | ---: | ---: | ---: | ---: |')

  const weakGradient = []
  for (const id of ids) {
    const raw = PRESET_THEMES[id].colors
    const c = normalizeThemeColors(raw)
    const r1 = contrastRatio(c.textMain, c.bgColor)
    const r2 = contrastRatio(c.textSoft, c.bgColor)
    const r3 = contrastRatio(c.textMain, c.glassColor || c.bgColor)
    const r4 = contrastRatio(c.textSoft, c.glassColor || c.bgColor)
    const dist = hexDistance(c.bgColor, c.bgGradientEnd)
    if (dist < 35 && c.bgMode === 'linear') weakGradient.push(id)
    push(
      `| ${PRESET_THEMES[id].name} (\`${id}\`) | ${r1.toFixed(2)} | ${r2.toFixed(2)} | ${r3.toFixed(2)} | ${r4.toFixed(2)} | ${dist.toFixed(1)} |`
    )
  }

  push('\n## Pairwise accent similarity (cosine of stacked accent RGB; high = may feel alike)\n')
  const fps = {}
  for (const id of ids) {
    fps[id] = accentFingerprint(normalizeThemeColors(PRESET_THEMES[id].colors))
  }
  push('| A | B | cosine |')
  push('| --- | --- | ---: |')
  const similar = []
  for (let i = 0; i < ids.length; i++) {
    for (let j = i + 1; j < ids.length; j++) {
      const a = ids[i]
      const b = ids[j]
      const cos = cosineSimilarity(fps[a], fps[b])
      if (cos >= 0.965) {
        similar.push([a, b, cos])
        push(`| ${a} | ${b} | ${cos.toFixed(3)} |`)
      }
    }
  }
  if (similar.length === 0) push('_(No pairs ≥ 0.965 — accent triplets are fairly distinct.)_')

  push('\n## Weak linear gradient (bg vs end ΔRGB < 35)\n')
  push(
    weakGradient.length
      ? `Themes: ${weakGradient.map((x) => `\`${x}\``).join(', ')} — gradient is subtle; rely on glow or bump end color.`
      : '_None under this threshold._'
  )

  push('\n---\n_Screenshots are manual; re-run this script after changing `PRESET_THEMES`._\n')

  if (process.env.THEME_AUDIT_MD === '1' || process.argv.includes('--write')) {
    const out = join(__dirname, 'theme-audit-report.md')
    writeFileSync(out, lines.join('\n'), 'utf8')
    console.log(`\nWrote ${out}`)
  }
}

main()
